#config-map
##########################
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  host: mysql-service
  user: root
  port: '3306'

---
#secrets
##########################
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
data:
  password: YWJjZDEyMzQ=


---
#sts
##########################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          resources:
          limits:
            memory: "256Mi"
            cpu: "750m"
          requests:
            memory: "128Mi"
            cpu: "500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret1
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/sql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

    


---
#service-for-sts
##########################
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP


---
#deployment-app-code
##########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: helloyogendra/custom-web:1.1
        ports:
          - containerPort: 4000
            name: http-web
        env:
        - name: DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: port
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret1
              key: password
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      volumes:
        - name: config-volume
          configMap:
            name: configmap1
        - name: secret-volume
          secret:
            secretName: secret1



---
#service-for-deployment
##########################
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
  - port: 4000
    protocol: TCP
    targetPort: http-web

