apiVersion: v1
kind: Pod
metadata:
  name: demo-quota-ns
  labels:
    name: demo-quota
spec:
  containers:
  - name: demo-quota-app
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
