apiVersion: v1
kind: Pod
metadata:
  name: demo-quota-ns2
  labels:
    name: demo-quota
spec:
  containers:
  - name: demo-quota-app2
    image: redis
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"
