apiVersion: v1
kind: Pod
metadata:
  name: cpu-fine
spec:
  containers:
    - name: ctr
      image: vish/stress
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "2.1"
        requests:
          cpu: "1.5"
      args: ["-cpus", "2"]
