apiVersion: v1
kind: Pod
metadata:
  name: memory-greedy
spec:
  containers:
    - name: ctr
      image: polinux/stress
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "1250M", "--vm-hang", "1"]
