apiVersion: v1
kind: Pod
metadata:
  name: test-app
spec:
  containers:
    - name: test
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |-
          echo start
          for i in 1 2 3 4; do
            echo in progress $i...
            sleep 1
          done
          echo finish
