apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-storage 


#To-Do::
# additional example - pv mapped with deployment
# - deployment will have 4/5 pods
# - go inside one pod, use 'exec'
# - go to the mapped path
# - try to modify the index.html
# - exit from this pod
# - go inside other pod, use 'exec'
# - check your index.html
# - delete deployement, associated pods will be deleted
# - again create a new deployment, edit the existing example
# - use the same pv/pvc objects
# - verify data

