apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy1
  labels:
    app: ngx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 4
  selector:
    matchLabels:
      app: ngx
  template:
    metadata:
      labels:
        app: ngx
    spec:
      containers:
      - name: myapp
        image: nginx:1.22
        ports:
        - containerPort: 80


# Here Observe strategy: type: RollingUpdate
# No downtime, update the associated Pods one by one while handling the traffic

# maxUnavailable - the number of Pods will not be available during the update process

# maxSurge - the number of Pods that can be created additionally on top of the desired amount of pods while an update is in progress (update is rolling-out)


# to test the rolling-update(updaing the pods associated with this deployment) part multiple times change the image version and run the apply command again.
