apiVersion: v1
kind: Pod
metadata:
  name: cpu-greedy
spec:
  containers:
    - name: ctr
      image: vish/stress
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "750m"
        requests:
          cpu: "0.5"
      args: ["-cpus", "2"]
