apiVersion: v1
kind: Pod
metadata:
  name: memory-over
spec:
  containers:
    - name: ctr
      image: polinux/stress
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1000Gi"
        requests:
          memory: "1000Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
