apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo1
  labels:
    app: web
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: my-container1
          image: nginx