apiVersion: v1
kind: Pod
metadata:
  name: demo-pod1
  labels:
    env: dev
spec:
  containers:
  - name: my-container2
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: demo-pod2
  labels:
    env: dev
spec:
  containers:
  - name: my-container3
    image: nginx


# Here we are trying to create these pods independently
# means no owner reference or controller specified
# observe - earlier we created a replicaset and these two pods have matching labels with the selector specified in the replicaset specs.
