apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-cpu-limit
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
  


  # Controlling the resources for a namespace level
  # first create a namespace
  # create a resourcequota object - example this yaml file
  # map this resourcequota with your namespace
  # now try to create new pods in this namespace