apiVersion: v1
kind: Pod
metadata:
  name: demo2
  labels:
    key1: value1
    env: dev
    app: web
spec:
  restartPolicy: Never
  containers:
    - name: ngx-app
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
