apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
    release: main
spec:
  containers:
    - name: abcd
      image: httpd:2.4
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
