apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-app
  labels:
    name: secret-demo-app
spec:
  containers:
  - name: secret-demo-app
    image: redis
    volumeMounts:
      - name: mysecret
        mountPath: "/etc/newsecret"
        readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret