apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp
        image: nginx:1.22
        ports:
        - containerPort: 80



# Here Observe strategy: type: Recreate
# downtime is there, terminate the associated Pods at once and recreate the replicas/pods with new updates mentioned. 